export const GET_ERRORS = "GET_ERRORS";
export const UPDATE_ERRORS = "UPDATE_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const FETCH_POSTS = "FETCH_POSTS";
export const LOADING = "LOADING";
export const APPROVE_VOTE_COMPLETE = "VOTE_COMPLETE";
export const FAKE_VOTE_COMPLETE = "FAKE_VOTE_COMPLETE";
export const MIX_VOTE_COMPLETE = "MIX_VOTE_COMPLETE";
export const VOTE_ERROR = "VOTE_ERROR";
export const INCREMENT_PAGE = "INCREMENT_PAGE";
export const NO_MORE = "NO_MORE";
